language: python
python:
    - "2.7"
addons:
  apt:
    packages:
      - swig
env:
    matrix:
        - TOXENV=py27-dj14
        - TOXENV=py27-dj15
        - TOXENV=py27-dj16
        - TOXENV=py27-dj17
        - TOXENV=py27-dj18
install:
   - pip install tox
script: tox
